services:
  - type: web
    name: swarm-io-hhbadak-live
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./deployment/render-free/Dockerfile
    dockerContext: .
    healthCheckPath: /health/ready
    autoDeployTrigger: commit
    envVars:
      - fromGroup: swarm-io-shared
      - key: SWARM_DB_PROVIDER
        value: MySql
      - key: SWARM_AUTO_CREATE_DATABASE
        value: "true"
      - key: SWARM_ADMIN_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false

envVarGroups:
  - name: swarm-io-shared
    envVars:
      - key: SWARM_TOKEN_SECRET
        generateValue: true
